-- MySQL Schema converted from PostgreSQL
-- Generated on: 2025-09-25T10:50:31.121Z

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `profiles` (
  `id` char(36) NOT NULL,
  `email` varchar NOT NULL,
  `full_name` varchar NOT NULL,
  `role` varchar NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `staff_code` text,
  `position` text,
  `phone` text,
  `department_id` text,
  `badge_id` text,
  `profile_image_url` text,
  `is_staff` tinyint(1) NOT NULL,
  `staff_active` tinyint(1) NOT NULL,
  `bio` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `inventory_products` (
  `id` char(36) NOT NULL,
  `user_id` char(36) NOT NULL,
  `part_number` varchar NOT NULL,
  `description` varchar NOT NULL,
  `unit_of_measure` varchar NOT NULL,
  `minimum_stock` text,
  `reorder_point` text,
  `unit_cost` decimal NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `bin_no` varchar NOT NULL,
  `reorder_qty` text,
  `purchase_price` decimal NOT NULL,
  `sale_markup` int NOT NULL,
  `sale_price` int NOT NULL,
  `stock_category` text,
  `open_balance` text,
  `open_bal_date` text,
  `active` tinyint(1) NOT NULL,
  `department_id` text,
  `superseding_no` text,
  `rack` text,
  `row_position` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `inventory_batches` (
  `id` char(36) NOT NULL,
  `user_id` char(36) NOT NULL,
  `product_id` char(36) NOT NULL,
  `batch_number` varchar NOT NULL,
  `quantity` int NOT NULL,
  `location` text,
  `url` text,
  `expiry_date` text,
  `received_date` varchar NOT NULL,
  `supplier_id` text,
  `purchase_order` text,
  `cost_per_unit` text,
  `notes` text,
  `status` varchar NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `approval_status` varchar NOT NULL,
  `approved_by` text,
  `approved_at` text,
  `job_allocated_to` text,
  `job_allocated_by` text,
  `job_allocated_at` text,
  `supplier_invoice_number` varchar NOT NULL,
  `entered_by` text,
  `receipt_id` varchar NOT NULL,
  `department_id` text,
  `buying_price` decimal NOT NULL,
  `sale_markup_percent` int NOT NULL,
  `sale_markup_value` decimal NOT NULL,
  `selling_price` decimal NOT NULL,
  `lpo` text,
  `reference_no` varchar NOT NULL,
  `batch_date` varchar NOT NULL,
  `bin_no` text,
  `the_size` text,
  `dollar_rate` int NOT NULL,
  `freight_rate` int NOT NULL,
  `total_rate` int NOT NULL,
  `dollar_amount` decimal NOT NULL,
  `core_value` text,
  `aircraft_reg_no` text,
  `batch_id_a` text,
  `batch_id_b` text,
  `received_by` varchar NOT NULL,
  `receive_code` text,
  `verified_by` text,
  `verification_code` text,
  `core_id` text,
  `serial_no` text,
  `alternate_department_id` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `customers` (
  `id` char(36) NOT NULL,
  `user_id` char(36) NOT NULL,
  `name` varchar NOT NULL,
  `email` text,
  `phone` text,
  `address` text,
  `city` text,
  `state` text,
  `zip_code` varchar NOT NULL,
  `country` varchar NOT NULL,
  `aircraft_type` text,
  `tail_number` text,
  `contact_person` text,
  `notes` text,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `job_cards` (
  `jobcardid` int NOT NULL,
  `customerid` text,
  `customername` varchar NOT NULL,
  `custaddress` varchar NOT NULL,
  `custphone` varchar NOT NULL,
  `custfax` text,
  `category` varchar NOT NULL,
  `date_opened` datetime NOT NULL,
  `date_closed` text,
  `description` varchar NOT NULL,
  `parts_cost` text,
  `service_cost` text,
  `empid` text,
  `remarks` varchar NOT NULL,
  `custinvno` text,
  `parts_price` text,
  `assignedto` text,
  `preparedby` text,
  `preparedate` text,
  `approvedby` text,
  `approvedate` text,
  `dateforwarded` text,
  `aircraft_regno` varchar NOT NULL,
  `subjobcardid` text,
  `accomponentserno` text,
  `requisitiondate` text,
  `requestedby` text,
  `receivedby` text,
  `receiveddate` text,
  `authorisedby` text,
  `authoriseddate` text,
  `issuedby` text,
  `issueddate` text,
  `stockcardpostedby` text,
  `stockcardposteddate` text,
  `manual_jobno` text,
  `service_fitting_cost` text,
  `closed` text,
  `whbnc_cost` text,
  `whbnc_fitting` text,
  `close_invoice` text,
  `prepaid` text,
  `printed` text,
  `ac_aproved` text,
  `oss_approved` text,
  `consumables_approved` text,
  `ac_aproved_by` text,
  `oss_approved_by` text,
  `consumables_approved_by` text,
  `ac_forwarddate` text,
  `oss_forwarddate` text,
  `whb_forwarddate` text,
  `ac_approvedate` text,
  `oss_approvedate` text,
  `whb_approvedate` text,
  `whb_aproved_by` text,
  `whb_aproved` text,
  `ac_no` text,
  `oss_no` text,
  `whbnc_no` text,
  `user_id` char(36) NOT NULL,
  `warehouse_a_approved` tinyint(1) NOT NULL,
  `warehouse_bc_approved` tinyint(1) NOT NULL,
  `owner_supplied_approved` tinyint(1) NOT NULL,
  `warehouse_a_approved_by` text,
  `warehouse_bc_approved_by` text,
  `owner_supplied_approved_by` text,
  `warehouse_a_approved_at` text,
  `warehouse_bc_approved_at` text,
  `owner_supplied_approved_at` text,
  `job_status` varchar NOT NULL,
  `invoice_number` text,
  `finalized_at` text,
  `finalized_by` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_roles` (
  `id` char(36) NOT NULL,
  `user_id` char(36) NOT NULL,
  `role` varchar NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `customer_access_log` (
  `id` char(36) NOT NULL,
  `user_id` char(36) NOT NULL,
  `customer_id` char(36) NOT NULL,
  `action` varchar NOT NULL,
  `accessed_at` datetime NOT NULL,
  `ip_address` text,
  `user_agent` varchar NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `exchange_rates` (
  `id` char(36) NOT NULL,
  `base_currency` varchar NOT NULL,
  `target_currency` varchar NOT NULL,
  `rate` int NOT NULL,
  `last_updated` datetime NOT NULL,
  `manual_override` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `departments` (
  `id` char(36) NOT NULL,
  `user_id` char(36) NOT NULL,
  `department_name` varchar NOT NULL,
  `department_description` varchar NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
