name: Contrast Check

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  contrast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run contrast checks
        run: node scripts/contrast-check.mjs
